In [1]:
import numpy as np

zeros = np.zeros(10)

In [3]:
vowels = np.array(['a', 'e', 'i', 'o', 'u'])

In [5]:
ones = np.ones((2, 5), dtype=int)

In [7]:
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])

In [9]:
myarray2 = np.arange(4, 4 * 15 + 1, 4, dtype=float).reshape(3, 5)


In [11]:
arrays = [zeros, vowels, ones, myarray1, myarray2]
for arr in arrays:
    print(f"Array: {arr}")
    print("Dimensions:", arr.ndim)
    print("Shape:", arr.shape)
    print("Size:", arr.size)
    print("Data Type:", arr.dtype)
    print("Item Size:", arr.itemsize)
    print()

Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dimensions: 1
Shape: (10,)
Size: 10
Data Type: float64
Item Size: 8

Array: ['a' 'e' 'i' 'o' 'u']
Dimensions: 1
Shape: (5,)
Size: 5
Data Type: <U1
Item Size: 4

Array: [[1 1 1 1 1]
 [1 1 1 1 1]]
Dimensions: 2
Shape: (2, 5)
Size: 10
Data Type: int32
Item Size: 4

Array: [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: float64
Item Size: 8

Array: [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]
Dimensions: 2
Shape: (3, 5)
Size: 15
Data Type: float64
Item Size: 8



In [13]:
ones_reshaped = ones.reshape(1, 10)

In [15]:
print(vowels[1:3])


['e' 'i']


In [17]:
print(vowels[1:3])


['e' 'i']


In [19]:
print(myarray1[1:3, :])

[[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]


In [21]:
print(myarray1[:, 0:2])

[[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]


In [23]:
print(myarray1[1:3, 0])

[  3.4 -19. ]


In [25]:
vowels_reversed = vowels[::-1]

In [33]:
import numpy as np

zeros = np.zeros(10)

vowels = np.array(['a', 'e', 'i', 'o', 'u'])

ones = np.ones((2, 5), dtype=int)

myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])

myarray2 = np.arange(4, 64, 4, dtype=float).reshape(3, 5) 

print("Array attributes:")
for arr, name in zip([zeros, vowels, ones, myarray1, myarray2],
                     ["zeros", "vowels", "ones", "myarray1", "myarray2"]):
    print(f"{name} - dim: {arr.ndim}, shape: {arr.shape}, size: {arr.size}, "
          f"dtype: {arr.dtype}, itemsize: {arr.itemsize}")

ones_reshaped = ones.reshape(1, -1)
print("Reshaped ones:\n", ones_reshaped)

print("2nd and 3rd elements of vowels:", vowels[1:3])
print("Elements in the 2nd and 3rd rows of myarray1:\n", myarray1[1:3])
print("Elements in the 1st and 2nd columns of myarray1:\n", myarray1[:, :2])
print("Elements in the 1st column of the 2nd and 3rd rows of myarray1:\n", myarray1[1:3, 0])
print("Reversed vowels array:", vowels[::-1])

ones_divided = ones / 3
print("ones divided by 3:\n", ones_divided)

myarray1_padded = np.pad(myarray1, ((0, 0), (0, 2)), mode='constant')
print("Padded myarray1:\n", myarray1_padded)

add_arrays = myarray1_padded + myarray2
print("Addition of myarray1 and myarray2:\n", add_arrays)

subtract_arrays = myarray2 - myarray1_padded
print("Subtraction of myarray1 from myarray2:\n", subtract_arrays)

multiply_arrays = myarray1_padded * myarray2
print("Elementwise multiplication of myarray1 and myarray2:\n", multiply_arrays)

myarray1_matrix = np.random.rand(3, 5)  
myarray3 = np.dot(myarray1_matrix, myarray2.T)
print("Matrix multiplication result:\n", myarray3)

division_arrays = np.divide(myarray1_padded, myarray2, out=np.zeros_like(myarray1_padded), where=myarray2!=0)
print("Division of myarray1 by myarray2:\n", division_arrays)

cubed_myarray1 = np.power(myarray1, 3) / 2
print("Cubed myarray1 divided by 2:\n", cubed_myarray1)

sqrt_myarray2 = np.round(np.sqrt(myarray2) / 2, 2)
print("Square root of myarray2 divided by 2:\n", sqrt_myarray2)


Array attributes:
zeros - dim: 1, shape: (10,), size: 10, dtype: float64, itemsize: 8
vowels - dim: 1, shape: (5,), size: 5, dtype: <U1, itemsize: 4
ones - dim: 2, shape: (2, 5), size: 10, dtype: int32, itemsize: 4
myarray1 - dim: 2, shape: (3, 3), size: 9, dtype: float64, itemsize: 8
myarray2 - dim: 2, shape: (3, 5), size: 15, dtype: float64, itemsize: 8
Reshaped ones:
 [[1 1 1 1 1 1 1 1 1 1]]
2nd and 3rd elements of vowels: ['e' 'i']
Elements in the 2nd and 3rd rows of myarray1:
 [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
Elements in the 1st and 2nd columns of myarray1:
 [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]
Elements in the 1st column of the 2nd and 3rd rows of myarray1:
 [  3.4 -19. ]
Reversed vowels array: ['u' 'o' 'i' 'e' 'a']
ones divided by 3:
 [[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]
Padded myarray1:
 [[  2.7   0.   -2.    0.    0. ]
 [  3.4  10.6   0.    0.    0. ]
 [-19.   99.9  13.    0.    0

In [35]:
transpose_ones = ones.T
transpose_myarray2 = myarray2.T

print("Transpose of ones:\n", transpose_ones)
print("Transpose of myarray2:\n", transpose_myarray2)

sorted_vowels = np.sort(vowels)[::-1]
print("Sorted vowels in reverse order:", sorted_vowels)

sorted_myarray1 = np.sort(myarray1, axis=0)
print("Sorted myarray1 with the lowest values in the first row:\n", sorted_myarray1)

myarray4 = np.arange(-1, -1 + (14 * 3 * 0.25), 0.25).reshape(14, 3)
print("myarray4:\n", myarray4)

split_myarray4 = np.array_split(myarray4, 3)
print("Split myarray4 into 3 equal parts:")
for idx, part in enumerate(split_myarray4):
    print(f"Part {idx + 1}:\n", part)

total_sum = np.sum(myarray4)
print("Sum of all elements in myarray4:", total_sum)

row_sum = np.sum(myarray4, axis=1)
print("Row-wise sum of elements in myarray4:", row_sum)

col_sum = np.sum(myarray4, axis=0)
print("Column-wise sum of elements in myarray4:", col_sum)

max_value = np.max(myarray4)
print("Maximum value in myarray4:", max_value)

min_row_values = np.min(myarray4, axis=1)
print("Minimum values in each row of myarray4:", min_row_values)

mean_row_values = np.mean(myarray4, axis=1)
print("Mean of elements in each row of myarray4:", mean_row_values)

std_dev_col = np.std(myarray4, axis=0)
print("Column-wise standard deviation of elements in myarray4:", std_dev_col)


Transpose of ones:
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Transpose of myarray2:
 [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]
Sorted vowels in reverse order: ['u' 'o' 'i' 'e' 'a']
Sorted myarray1 with the lowest values in the first row:
 [[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]
myarray4:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]
Split myarray4 into 3 equal parts:
Part 1:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]
Part 2:
 [[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]
Part 3:
 [[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]
Sum of all elements in myarray

In [37]:
total_sum = np.sum(myarray4)
print("Sum of all elements in myarray4:", total_sum)

row_sum = np.sum(myarray4, axis=1)
print("Row-wise sum of elements in myarray4:", row_sum)

col_sum = np.sum(myarray4, axis=0)
print("Column-wise sum of elements in myarray4:", col_sum)

max_value = np.max(myarray4)
print("Maximum value in myarray4:", max_value)

min_row_values = np.min(myarray4, axis=1)
print("Minimum values in each row of myarray4:", min_row_values)

mean_row_values = np.mean(myarray4, axis=1)
print("Mean of elements in each row of myarray4:", mean_row_values)

std_dev_col = np.std(myarray4, axis=0)
print("Column-wise standard deviation of elements in myarray4:", std_dev_col)


Sum of all elements in myarray4: 173.25
Row-wise sum of elements in myarray4: [-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]
Column-wise sum of elements in myarray4: [54.25 57.75 61.25]
Maximum value in myarray4: 9.25
Minimum values in each row of myarray4: [-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]
Mean of elements in each row of myarray4: [-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]
Column-wise standard deviation of elements in myarray4: [3.02334666 3.02334666 3.02334666]


In [43]:
import numpy as np

riyadh_coords = np.array([24.7136, 46.6753])

capitals = np.array([
    ["Washington, D.C.", 38.9072, -77.0369],
    ["London", 51.5074, -0.1278],
    ["Berlin", 52.52, 13.4050],
    ["Tokyo", 35.6762, 139.6503],
    ["Paris", 48.8566, 2.3522],
])

capital_coords = capitals[:, 1:].astype(float)

distances = np.linalg.norm(capital_coords - riyadh_coords, axis=1)

min_distance_index = np.argmin(distances)
closest_capital = capitals[min_distance_index]

print(f"The closest capital city to Riyadh is {closest_capital[0]} with a distance of {distances[min_distance_index]:.2f} units.")


The closest capital city to Riyadh is Berlin with a distance of 43.36 units.


In [47]:
myarray2_reshaped = myarray2[:, :3] 

add_arrays = myarray1 + myarray2_reshaped

In [49]:
ones_transposed = ones.T
myarray2_transposed = myarray2.T

print("Transposed ones array:\n", ones_transposed)
print("Transposed myarray2:\n", myarray2_transposed)

Transposed ones array:
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Transposed myarray2:
 [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]


In [51]:
sorted_vowels = np.sort(vowels)[::-1]
print("Sorted vowels array in reverse order:", sorted_vowels)

Sorted vowels array in reverse order: ['u' 'o' 'i' 'e' 'a']


In [53]:
sorted_myarray1 = np.sort(myarray1, axis=0)
print("Sorted myarray1 by columns:\n", sorted_myarray1)

Sorted myarray1 by columns:
 [[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


In [55]:
myarray4 = np.arange(-1, -1 + 14 * 3 * 0.25, 0.25).reshape(14, 3)
print("myarray4:\n", myarray4)

myarray4:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]


In [59]:
myarray4 = np.arange(-1, -1 + 14 * 3 * 0.25, 0.25).reshape(14, 3)
print("myarray4:\n", myarray4)

split_array = np.array_split(myarray4, 3, axis=0)
print("Split myarray4 into 3 parts:")

for i, part in enumerate(split_array):
    print(f"Part {i+1}:\n", part)


myarray4:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]
Split myarray4 into 3 parts:
Part 1:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]
Part 2:
 [[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]
Part 3:
 [[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]


In [61]:
total_sum = np.sum(myarray4)
print(f"Sum of all elements: {total_sum}")

row_sum = np.sum(myarray4, axis=1)
print(f"Sum of elements row-wise:\n{row_sum}")

col_sum = np.sum(myarray4, axis=0)
print(f"Sum of elements column-wise:\n{col_sum}")

max_value = np.max(myarray4)
print(f"Maximum value in myarray4: {max_value}")

min_value_row = np.min(myarray4, axis=1)
print(f"Minimum value in each row:\n{min_value_row}")

mean_value_row = np.mean(myarray4, axis=1)
print(f"Mean value in each row:\n{mean_value_row}")

std_dev_col = np.std(myarray4, axis=0)
print(f"Standard deviation column-wise:\n{std_dev_col}")


Sum of all elements: 173.25
Sum of elements row-wise:
[-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]
Sum of elements column-wise:
[54.25 57.75 61.25]
Maximum value in myarray4: 9.25
Minimum value in each row:
[-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]
Mean value in each row:
[-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]
Standard deviation column-wise:
[3.02334666 3.02334666 3.02334666]


In [63]:
import numpy as np

riyadh_coordinates = np.array([24.7136, 46.6753])  

capital_cities = {
    'Cairo': np.array([30.0330, 31.2330]),
    'London': np.array([51.5074, -0.1278]),
    'Paris': np.array([48.8566, 2.3522]),
    'New York': np.array([40.7128, -74.0060]),
    'Tokyo': np.array([35.6762, 139.6503])
}

distances = {}
for city, coordinates in capital_cities.items():
    distance = np.linalg.norm(coordinates - riyadh_coordinates) 
    distances[city] = distance

closest_city = min(distances, key=distances.get)
closest_city_distance = distances[closest_city]

print(f"The closest capital city to Riyadh is {closest_city} with a distance of {closest_city_distance:.2f} km.")


The closest capital city to Riyadh is Cairo with a distance of 16.33 km.


In [65]:
import numpy as np

washington_coordinates = np.array([38.9072, -77.0369])

capital_cities = {
    'Cairo': np.array([30.0330, 31.2330]),
    'London': np.array([51.5074, -0.1278]),
    'Paris': np.array([48.8566, 2.3522]),
    'New York': np.array([40.7128, -74.0060]),
    'Tokyo': np.array([35.6762, 139.6503]),
    'Berlin': np.array([52.5200, 13.4050]),
    'Rome': np.array([41.9028, 12.4964]),
    'Moscow': np.array([55.7558, 37.6173]),
    'Beijing': np.array([39.9042, 116.4074]),
    'Buenos Aires': np.array([-34.6037, -58.3816]),
    'Mexico City': np.array([19.4326, -99.1332]),
    'Sao Paulo': np.array([-23.5505, -46.6333]),
    'Seoul': np.array([37.5665, 126.9780]),
    'Madrid': np.array([40.4168, -3.7038])
}

distances = {}
for city, coordinates in capital_cities.items():
    distance = np.linalg.norm(coordinates - washington_coordinates) 
    distances[city] = distance

sorted_capitals = sorted(distances.items(), key=lambda item: item[1])

print("Top 10 Closest Capital Cities to Washington DC:")
for i in range(min(10, len(sorted_capitals))):
    city, distance = sorted_capitals[i]
    print(f"{i+1}. {city} - Coordinates: {capital_cities[city]} - Distance: {distance:.2f} km")

Top 10 Closest Capital Cities to Washington DC:
1. New York - Coordinates: [ 40.7128 -74.006 ] - Distance: 3.53 km
2. Mexico City - Coordinates: [ 19.4326 -99.1332] - Distance: 29.45 km
3. Sao Paulo - Coordinates: [-23.5505 -46.6333] - Distance: 69.46 km
4. Madrid - Coordinates: [40.4168 -3.7038] - Distance: 73.35 km
5. Buenos Aires - Coordinates: [-34.6037 -58.3816] - Distance: 75.84 km
6. London - Coordinates: [51.5074 -0.1278] - Distance: 77.93 km
7. Paris - Coordinates: [48.8566  2.3522] - Distance: 80.01 km
8. Rome - Coordinates: [41.9028 12.4964] - Distance: 89.58 km
9. Berlin - Coordinates: [52.52  13.405] - Distance: 91.46 km
10. Cairo - Coordinates: [30.033 31.233] - Distance: 108.63 km
